//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICalculatorService", CallbackContract=typeof(ICalculatorServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
public interface ICalculatorService
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalculatorService/Clear")]
    void Clear();
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalculatorService/Clear")]
    System.Threading.Tasks.Task ClearAsync();
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalculatorService/AddTo")]
    void AddTo(double n);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalculatorService/AddTo")]
    System.Threading.Tasks.Task AddToAsync(double n);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalculatorService/SubstractFrom")]
    void SubstractFrom(double n);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalculatorService/SubstractFrom")]
    System.Threading.Tasks.Task SubstractFromAsync(double n);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalculatorService/MultiplyBy")]
    void MultiplyBy(double n);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalculatorService/MultiplyBy")]
    System.Threading.Tasks.Task MultiplyByAsync(double n);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalculatorService/DivideBy")]
    void DivideBy(double n);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalculatorService/DivideBy")]
    System.Threading.Tasks.Task DivideByAsync(double n);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICalculatorServiceCallback
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalculatorService/Equal")]
    void Equal(double result);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalculatorService/Equation")]
    void Equation(string eqn);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICalculatorServiceChannel : ICalculatorService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CalculatorServiceClient : System.ServiceModel.DuplexClientBase<ICalculatorService>, ICalculatorService
{
    
    public CalculatorServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public CalculatorServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public CalculatorServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculatorServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculatorServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public void Clear()
    {
        base.Channel.Clear();
    }
    
    public System.Threading.Tasks.Task ClearAsync()
    {
        return base.Channel.ClearAsync();
    }
    
    public void AddTo(double n)
    {
        base.Channel.AddTo(n);
    }
    
    public System.Threading.Tasks.Task AddToAsync(double n)
    {
        return base.Channel.AddToAsync(n);
    }
    
    public void SubstractFrom(double n)
    {
        base.Channel.SubstractFrom(n);
    }
    
    public System.Threading.Tasks.Task SubstractFromAsync(double n)
    {
        return base.Channel.SubstractFromAsync(n);
    }
    
    public void MultiplyBy(double n)
    {
        base.Channel.MultiplyBy(n);
    }
    
    public System.Threading.Tasks.Task MultiplyByAsync(double n)
    {
        return base.Channel.MultiplyByAsync(n);
    }
    
    public void DivideBy(double n)
    {
        base.Channel.DivideBy(n);
    }
    
    public System.Threading.Tasks.Task DivideByAsync(double n)
    {
        return base.Channel.DivideByAsync(n);
    }
}
